In [23]:
import pydicom
import os
import numpy
from os import listdir
from os.path import isfile, join
import pandas as pd

In [9]:
target_folder = r"E:\Internship Mass storage\First 3 datasets\Duke_breast_MRI dataset\Duke-Breast-Cancer-MRI\Breast_MRI_002\01-01-1990-NA-MRI BREAST BILATERAL W  WO-51972\3.000000-ax t1-40797"
mypath = target_folder
onlyfiles = [f for f in listdir(mypath) if isfile(join(mypath, f))]
filepaths = [target_folder + "/" + s for s in onlyfiles]
print(filepaths)

['E:\\Internship Mass storage\\First 3 datasets\\Duke_breast_MRI dataset\\Duke-Breast-Cancer-MRI\\Breast_MRI_002\\01-01-1990-NA-MRI BREAST BILATERAL W  WO-51972\\3.000000-ax t1-40797/1-01.dcm', 'E:\\Internship Mass storage\\First 3 datasets\\Duke_breast_MRI dataset\\Duke-Breast-Cancer-MRI\\Breast_MRI_002\\01-01-1990-NA-MRI BREAST BILATERAL W  WO-51972\\3.000000-ax t1-40797/1-02.dcm', 'E:\\Internship Mass storage\\First 3 datasets\\Duke_breast_MRI dataset\\Duke-Breast-Cancer-MRI\\Breast_MRI_002\\01-01-1990-NA-MRI BREAST BILATERAL W  WO-51972\\3.000000-ax t1-40797/1-03.dcm', 'E:\\Internship Mass storage\\First 3 datasets\\Duke_breast_MRI dataset\\Duke-Breast-Cancer-MRI\\Breast_MRI_002\\01-01-1990-NA-MRI BREAST BILATERAL W  WO-51972\\3.000000-ax t1-40797/1-04.dcm', 'E:\\Internship Mass storage\\First 3 datasets\\Duke_breast_MRI dataset\\Duke-Breast-Cancer-MRI\\Breast_MRI_002\\01-01-1990-NA-MRI BREAST BILATERAL W  WO-51972\\3.000000-ax t1-40797/1-05.dcm', 'E:\\Internship Mass storage\\Firs

In [36]:
# got this code from: https://gist.github.com/somada141/8dd67a02e330a657cf9e
RefDs = pydicom.read_file(filepaths[0])
ConstPixelDims = (int(RefDs.Rows), int(RefDs.Columns), len(filepaths))
ConstPixelSpacing = (float(RefDs.PixelSpacing[0]), float(RefDs.PixelSpacing[1]), float(RefDs.SliceThickness))

In [14]:
ArrayDicom = numpy.zeros(ConstPixelDims, dtype=RefDs.pixel_array.dtype)

In [16]:
for filenameDCM in filepaths:
    # read the file
    ds = pydicom.read_file(filenameDCM)
    # store the raw image data
    ArrayDicom[:, :, filepaths.index(filenameDCM)] = ds.pixel_array

In [17]:
print(ds.pixel_array)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [24]:
df = pd.read_excel (r'E:\Internship Mass storage\First 3 datasets\Duke_breast_MRI dataset\Annotation_Boxes.xlsx')
print (df)

         Patient ID  Start Row  End Row  Start Column  End Column  \
0    Breast_MRI_001        234      271           308         341   
1    Breast_MRI_002        251      294           108         136   
2    Breast_MRI_003        351      412            82         139   
3    Breast_MRI_004        262      280           193         204   
4    Breast_MRI_005        188      213           138         178   
..              ...        ...      ...           ...         ...   
917  Breast_MRI_918        345      395           338         395   
918  Breast_MRI_919        285      312           369         397   
919  Breast_MRI_920        172      193           337         355   
920  Breast_MRI_921        328      374           404         446   
921  Breast_MRI_922        258      270           149         164   

     Start Slice  End Slice  
0             89        112  
1             59         72  
2             96        108  
3             86         95  
4             76     

In [32]:
test = df.iloc[1]
type(test)

pandas.core.series.Series

In [35]:
patient2 = pd.Series(test).values
pd.Series(test).values

array(['Breast_MRI_002', 251, 294, 108, 136, 59, 72], dtype=object)